name: Build & Test CI

on:
    push:
        branches: [develop]
    pull_request:
        branches: [main]

jobs:
    builds:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install dependencies
              run: yarn install
            - name: Build packages
              run: yarn build:prod
            - name: Automated tests
              run: yarn run test
            - name: Visual regression tests
              env:
                  CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
              run: yarn test:chromatic
